steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        git clone https://github.com/LongPham0/CF_test.git --no-checkout
        mv CF_test/.git .
        git diff --name-only --diff-filter=AMDR @~..@ | grep "/" | cut -d"/" -f1 | uniq > /workspace/diff

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./build.bash']
